name: run
description: Wrapper over `dart:io` [Process] API's that supports additional features.
version: 2025.426.2344
homepage:
repository: "https://github.com/dart-pkg/run"
environment:
  sdk: ^3.7.2
platforms:
  android:
  ios:
  linux:
  macos:
  #web:
  windows:
dependencies:
  std: ^2025.426.2248
dev_dependencies:
  lints: ^5.1.1
  output: ^2025.426.2027
  test: ^1.25.15
#executables:
#  run: main
