name: run
description: Wrapper over `dart:io` [Process] API's that supports additional features.
version: 2025.428.1720
homepage: 
repository: https://github.com/dart-pkg/run
environment:
  sdk: ^3.7.2
platforms:
  android: 
  ios: 
  linux: 
  macos: 
  # web:
  windows: 
topics:
  - cli
  - process
dependencies:
  std: ^2025.428.1703
dev_dependencies:
  lints: ^5.1.1
  output: ^2025.430.1731
  test: ^1.25.15
