name: run
description: Wrapper over `dart:io` [Process] API's that supports additional features.
version: 2025.609.2107
homepage: 
repository: https://github.com/dart-pkg/run
environment:
  sdk: ^3.7.2
platforms:
  android: 
  ios: 
  linux: 
  macos: 
  # web:
  windows: 
topics:
  - cli
  - process
dependencies:
  std: ^2025.609.455
dev_dependencies:
  lints: ^6.0.0
  output: ^2025.502.1958
  test: ^1.26.2
